#ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  database_url: mongodb://rootAdmin:rootAdmin123@mongodb-service:27017/Storage-Manager-System
  user_port: "5001"
  storage_port: "5002"
  order_port: "5003"
  delivery_port: "5004"

---
#User Service
apiVersion: v1
kind: Service
metadata:
  name: user-api
spec:
  selector:
    app: user-api
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      name: user-api

---
#Storage Service
apiVersion: v1
kind: Service
metadata:
  name: storage-api
spec:
  selector:
    app: storage-api
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      name: storage-api

---
#Order Service
apiVersion: v1
kind: Service
metadata:
  name: order-api
spec:
  selector:
    app: order-api
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
      name: order-api

---
#Delivery Service
apiVersion: v1
kind: Service
metadata:
  name: delivery-api
spec:
  selector:
    app: delivery-api
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
      name: delivery-api

---
#Deploy User-api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: user:1.0.0
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: database_url
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: user_port
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 200m

---
#Deploy Storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-api
  template:
    metadata:
      labels:
        app: storage-api
    spec:
      containers:
        - name: storage-api
          image: storage:1.0.0
          ports:
            - containerPort: 5002
          env:
            - name: MONGO_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: database_url
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: storage_port
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 200m

---
#Deploy Order
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - name: order-api
          image: order:1.0.0
          ports:
            - containerPort: 5003
          env:
            - name: MONGO_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: database_url
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: order_port
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 200m

---
#Deploy Delivery
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-api
  template:
    metadata:
      labels:
        app: delivery-api
    spec:
      containers:
        - name: delivery-api
          image: delivery:1.0.0
          ports:
            - containerPort: 5004
          env:
            - name: MONGO_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: database_url
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: delivery_port
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 200m

---
#Scale Config User
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-api-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10

---
#Scale Config Storage
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: storage-api-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: storage-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10

---
#Scale Config Order
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-api-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10

---
#Scale Config Delivery
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: delivery-api-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: delivery-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10