# Mongodb Persistens
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# Mongodb Secret
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-password: cGFzc3dvcmQxMjM=
  mongodb-root-username: YWRtaW5Vc2Vy

---
# Mongodb Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
# Mongodb Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  init.js: |
    db = new Mongo().getDB("Storage-Manager-System");
    db.createCollection("users", { capped: false });
    db.createCollection("storage", { capped: false });
    db.createCollection("delivery", { capped: false });
    db.createCollection("orders", { capped: false });

    db.createRole({
      role: "admin",
      privileges: [
        {
          resource: {
            db: "Storage-Manager-System",
            collection: ""
          },
          actions: ["find", "update", "insert", "remove"]
        }
      ],
      roles: []
    });

    db.createUser({
      user: "rootAdmin",
      pwd: "rootAdmin123",
      roles: [
        {
          role: "admin",
          db: "Storage-Manager-System"
        }
      ]
    });

    db.storage.insertMany([
      {
        productName: "SzuperPhone X1",
        productCode: "SPX1001",
        description: "Forradalmi okostelefon a legújabb technológiával.",
        quantity: 50,
        unitPrice: 750,
        category: "Elektronika",
        supplier: "TechMánia",
        location: "A3"
      },
      {
        productName: "UltraBook Pro",
        productCode: "UBP2023",
        description: "Könnyű és erős laptop professzionális felhasználóknak.",
        quantity: 30,
        unitPrice: 1300,
        category: "Elektronika",
        supplier: "GadgetMaster",
        location: "B2"
      },
      {
        productName: "ZeneMániás Fülhallgató",
        productCode: "ZMFH005",
        description: "Kiváló minőségű fülhallgató mély basszusokkal.",
        quantity: 80,
        unitPrice: 85,
        category: "Elektronika",
        supplier: "AudioMágia",
        location: "C1"
      },
      {
        productName: "Gamer Elite Billentyűzet",
        productCode: "GEB400",
        description: "Mechanikus billentyűzet gyors reakcióidővel.",
        quantity: 20,
        unitPrice: 120,
        category: "Elektronika",
        supplier: "GameZoneTech",
        location: "D4"
      },
      {
        productName: "Full HD Monitor",
        productCode: "FHD250",
        description: "23 hüvelykes monitor éles képminőséggel.",
        quantity: 60,
        unitPrice: 200,
        category: "Elektronika",
        supplier: "DisplayWonders",
        location: "E2"
      },
      {
        productName: "SlimBook Air",
        productCode: "SBA2023",
        description: "Vékony és könnyű noteszgép mindennapi használatra.",
        quantity: 50000,
        unitPrice: 950,
        category: "Elektronika",
        supplier: "TechMánia",
        location: "A5"
      },
      {
        productName: "Okosotthon Kezdőcsomag",
        productCode: "OKC100",
        description: "Automatizált otthoni eszközök kezdőcsomagja.",
        quantity: 10,
        unitPrice: 300,
        category: "Elektronika",
        supplier: "SmartLiving",
        location: "B1"
      },
      {
        productName: "High-End Hangprojektor",
        productCode: "HPJ700",
        description: "Virtuális térhangzás élményt nyújtó hangprojektor.",
        quantity: 50000,
        unitPrice: 1200,
        category: "Elektronika",
        supplier: "AudioMágia",
        location: "C3"
      },
      {
        productName: "UltraSport Okosóra",
        productCode: "USO550",
        description: "Vízálló okosóra sportoláshoz és mindennapi viselethez.",
        quantity: 35,
        unitPrice: 180,
        category: "Elektronika",
        supplier: "GadgetMaster",
        location: "D2"
      },
      {
        productName: "Mini Drone X3",
        productCode: "MDX301",
        description: "Kompakt drón HD kamerával és könnyű irányíthatósággal.",
        quantity: 15,
        unitPrice: 250,
        category: "Elektronika",
        supplier: "TechFly",
        location: "E4"
      }
    ]);

    db.users.insertOne({
      _id: new ObjectId("651a75096fff21c7751b38bf"),
      email: "korom01tamas@gmail.com",
      firstName: "Tamás",
      lastName: "Korom",
      password: "480aeb42d7b1e3937fe8db12a1ffe6d8",
      address: "S. N. K. U. 2",
      city: "Miskolc",
      mobile: "06209993596",
      zipCode: "3527"
    });

---
# Mongodb Statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: config-volume
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
        - name: config-volume
          configMap:
            name: mongodb-configmap
            items:
              - key: init.js
                path: init.js