#mongoose secret
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-username: YWRtaW5Vc2Vy
  mongodb-password: cGFzc3dvcmQxMjM=

---
#mongoose configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-express-configmap
data:
  database_url: mongodb-service

---
#mongoose service
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service
spec:
  selector:
    app: mongodb-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30010
  type: NodePort

---
#mongoose deployment
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongodb-express-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-express
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
        - name: mongodb-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-express-configmap
                  key: database_url