version: '3.9'
services:

  user:
    container_name: "USER-API"
    ports:
      - "5001:5001"
    build: 
      context: ../USER_API/
    volumes:
      - ../USER_API/:/app
      - /app/node_modules
    env_file:
      - ./env/user-api.dev.env
    depends_on:
      mongo:
        condition: service_healthy

  storage:
    container_name: "STORAGE-API"
    ports:
      - "5002:5002"
    build: 
      context: ../STORAGE_API/
    volumes:
      - ../STORAGE_API/:/app
      - /app/node_modules
    env_file:
      - ./env/storage.dev.env
    depends_on:
      mongo:
        condition: service_healthy

  order:
    container_name: "ORDER-API"
    ports:
      - "5003:5003"
    build: 
      context: ../ORDER_API/
    volumes:
      - ../ORDER_API/:/app
      - /app/node_modules
    env_file:
      - ./env/order.dev.env
    depends_on:
      mongo:
        condition: service_healthy

  delivery:
    container_name: "DELIVERY-API"
    ports:
      - "5004:5004"
    build: 
      context: ../DELIVERY_API/
    volumes:
      - ../DELIVERY_API/:/app
      - /app/node_modules
    env_file:
      - ./env/delivery.dev.env
    depends_on:
      mongo:
        condition: service_healthy

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - delivery
      - user
      - order
      - storage

  mongo:
    container_name: mongo
    build: 
      context: ./mongo/
    volumes:
      - mongo_data:/data/db:Z
      - ./mongo/Init/init.js:/docker-entrypoint-initdb.d/init.js
    env_file:
      - ./env/mongodb.dev.env
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "-u", "adminUser", "-p", "password123", "--quiet", "--eval", "'db.stat().ok'"]
      interval: 5s

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    env_file:
      - ./env/mongoexpress.dev.env
    ports:
      - "3010:8081"
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data: