version: '1.0'
services:

  user:
    image: user:latest
    container_name: "USER-API"
    ports:
      - "5001:5001"
    build: 
      context: ../USER_API/
    volumes:
      - ../USER_API/:/app
      - /app/node_modules

  storage:
    image: storage:latest
    container_name: "STORAGE-API"
    ports:
      - "5002:5002"
    build: 
      context: ../STORAGE_API/
    volumes:
      - ../STORAGE_API/:/app
      - /app/node_modules

  order:
    image: order:latest
    container_name: "ORDER-API"
    ports:
      - "5003:5003"
    build: 
      context: ../ORDER_API/
    volumes:
      - ../ORDER_API/:/app
      - /app/node_modules

  delivery_and_billing:
    image: delivery_and_billing:latest
    container_name: "DELIVERY-AND-BILLING-API"
    ports:
      - "5004:5004"
    build: 
      context: ../DELIVERY_AND_BILLING_API/
    volumes:
      - ../DELIVERY_AND_BILLING_API/:/app
      - /app/node_modules

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    build: 
      context: ./mongo/
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: